In [1]:
import pandas as pd
import os

## Read file csv and summary

In [2]:
df = pd.read_csv('hotel_urls.csv')

print("Data shape: ", df.shape)

print("5 first rows")
display(df.head(5))

print("5 last rows")
display(df.tail(5))

display(df.info())

Data shape:  (2296, 6)
5 first rows

,name,url,id,rating_score,review_count,address
0,Khách sạn Caro Premium Đà Nẵng (Caro Premium D...,https://www.agoda.com/vi-vn/caro-premium-danan...,72076127,9.4,1372.0,"Phước Mỹ, Đà Nẵng - cách trung tâm 0,6 km"
1,DLG Hotel Danang,https://www.agoda.com/vi-vn/dlg-hotel-danang_2...,5835783,9.0,5489.0,"Phước Mỹ, Đà Nẵng - cách trung tâm 2,3 km"
2,Dragon Hotel & Apartments Đà Nẵng (Dragon Ho...,https://www.agoda.com/vi-vn/dragon-hotel-apart...,30913886,7.2,127.0,"Phước Mỹ, Đà Nẵng - cách trung tâm 0,8 km"
3,Khách sạn Elite Luxury by Elite24 (Elite Luxur...,https://www.agoda.com/vi-vn/elite-luxury-hotel...,75242528,8.4,400.0,"Hải Châu, Đà Nẵng - Nội thành"
4,Biệt thự Fanta Suite (Fanta Suite Villa),https://www.agoda.com/vi-vn/fanta-suite-villa/...,4858029,8.3,1159.0,"Phước Mỹ, Đà Nẵng - cách trung tâm 1,9 km"

5 last rows

,name,url,id,rating_score,review_count,address
2291,"Căn hộ 60 m² 1 phòng ngủ, 1 phòng tắm riêng ở ...",https://www.agoda.com/vi-vn/stargazer-hotel-h3...,31678265,2.0,1.0,"Hải Châu, Đà Nẵng - Nội thành"
2292,"Chung cư 40 m² 1 phòng ngủ, 2 phòng tắm riêng ...",https://www.agoda.com/vi-vn/friendly-home-by-t...,15851052,NaN,NaN,"Phước Mỹ, Đà Nẵng - cách trung tâm 2,9 km"
2293,"Biệt thự 300 m² 3 phòng ngủ, 3 phòng tắm riêng...",https://www.agoda.com/vi-vn/the-point-villa-5-...,4947606,8.5,45.0,"Hòa Hải, Đà Nẵng - cách trung tâm 11,2 km"
2294,Rung Huong Apartment,https://www.agoda.com/vi-vn/rung-huong-apartme...,33561821,NaN,NaN,"Hòa Hải, Đà Nẵng - cách trung tâm 3,7 km"
2295,"Biệt thự 500 m² 6 phòng ngủ, 6 phòng tắm riêng...",https://www.agoda.com/vi-vn/ocean-villa-da-nan...,72383118,NaN,NaN,"Hòa Hải, Đà Nẵng - cách trung tâm 11,3 km"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2296 entries, 0 to 2295
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          2296 non-null   object
 1   url           2289 non-null   object
 2   id            2296 non-null   int64
 3   rating_score  1576 non-null   float64
 4   review_count  1576 non-null   float64
 5   address       2296 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 107.8+ KB

None

## Check duplicate

In [3]:
print("The number of duplicate: ", df.duplicated().sum())

The number of duplicate:  0

## Check missing data

In [4]:
print(df.isnull().sum())

name              0
url               7
id                0
rating_score    720
review_count    720
address           0
dtype: int64

- Given the large number of hotels and the importance of the missing attribute, we have decided to delete the rows with missing data.

In [5]:
df = df.dropna()

print("Data shape after deletion", df.shape)

Data shape after deletion (1572, 6)

## Filter hotel

In [6]:
print("Number of hotels with at least 100 reviews: ", len(df[df['review_count'] >= 100]))

Number of hotels with at least 100 reviews:  682

- We assume that hotels with at least 100 reviews provide a more diverse and comprehensive range of sentiments and aspects. Given the substantial number of hotels meeting this criteria, we have decided to exclude those with fewer than 100 reviews to ensure data quality.

In [7]:
df = df.drop(df[df['review_count'] < 100].index)

df = df.drop(df[df['review_count'] > 1000].index)

print("Data shape after deletion", df.shape)

Data shape after deletion (402, 6)

## Export file csv

In [8]:
os.makedirs("../processed_data", exist_ok=True)
df.to_csv("../processed_data/hotel_urls.csv", index=False, encoding='utf-8-sig')

print("File saved successfully")

File saved successfully